name: Build Desktop Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: blacksmith-8vcpu-windows-2025

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # Setup Rust
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Linux dependencies
      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt update

          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      # Install JS dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Build app
      - name: Build desktop app
        run: |
          cd apps/web
          pnpm run desktop:build

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            apps/web/src-tauri/target/release/bundle
